networks:
 default:
   name: elastic
   external: false

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=e-wallet
    ports:
      - "5434:5432"

  redis:
    image: redis:7.2-alpine
    environment:
      - REDIS_PORT=6379
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - logs:/app/logs
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/e-wallet?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
  
  app-scheduler:
    image: e-wallet-scheduler:latest
    volumes:
      - logs:/app/logs
    depends_on:
      - app
      - redis
    ports:
      - "8082:8082"
  
  app-queue:
    image: e-wallet-queue:latest
    volumes:
      - logs:/app/logs
    depends_on:
      - app
      - redis
    ports:
      - "8081:8081"
    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
  
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    user: "0"
    command: >
      bash -c '
        echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:Nqy0fHREsStfASF" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"Nqy0fHREsStfASF\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=Nqy0fHREsStfASF
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    depends_on:
      - setup

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=Nqy0fHREsStfASF
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.1
    user: root
    command: filebeat -e -strict.perms=false
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=Nqy0fHREsStfASF
      - ELASTIC_HOSTS=http://elasticsearch:9200
      - KIBANA_HOSTS=http://kibana:5601
    volumes:
      - logs:/usr/share/filebeat/logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - "./filebeat_ingest_data/:/usr/share/filebeat/ingest_data/"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - elasticsearch
      - app

volumes:
  esdata:
  logs:
  kibanadata: